refactor: more modular code/functions (#150)
* more modular code/functions

* for loops

* play_url immediately

Co-authored-by: Euro <no>

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -411,7 +411,7 @@ download_thumbnails () {
 	local thumb_urls="$(printf "%s" "$*" |\
 	jq  -r '.[]|(.thumbs,.videoID)' )"
 	i=0
-	while read -r line; do
+	for line in $thumb_urls; do
 		if [ $((i % 2)) -eq 0 ]; then
 			local url="$line"
 			sleep 0.001
@@ -422,9 +422,7 @@ download_thumbnails () {
 			} &
 		fi
 		i=$((i + 1))
-done << EOF
-$thumb_urls
-EOF
+done 
 
 }
 get_sp_filter () {
@@ -638,7 +636,6 @@ get_search_query () {
 }
 #> To select videos from videos_data
 user_selection () {
-	[ "$is_url" -eq 1 ] && return
 	#remove subscription separators
 	local videos_data_clean="$(printf "%s" "$videos_data" | sed "/.*""$(printf "\t")""$/d" )"
 
@@ -667,7 +664,9 @@ user_selection () {
 	else
 		selected_data="$( video_menu "$videos_data" )"
 	fi
+}
 
+format_user_selection () {
 	#gets a list of video ids/urls from the selected data
 	local shorturls="$(printf "%s" "$selected_data" | sed -E -n -e "s_.*\|([^|]+) *\$_\1_p")"
 	[ -z "$shorturls" ] && exit;
@@ -676,22 +675,25 @@ user_selection () {
 	#through this loop, the selected data which was truncated by formatting is retrived.
 	selected_urls=""
 	selected_data=""
-	while read -r surl; do
+	for surl in $shorturls; do
 		[ -z "$surl" ] && continue
 		selected_urls="$(printf '%s\n%s' "$selected_urls" "https://www.youtube.com/watch?v=$surl")"
 		selected_data="$(printf '%s\n%s' "$selected_data" "$(printf "%s" "$videos_data" | grep -m1 -e "$surl" )")"
-	done << EOF
-	$shorturls
-EOF
+	done 
 	selected_urls="$( printf "%s" "$selected_urls" | sed 1d )"
 	#sometimes % shows up in selected data, could throw an error if it's an invalid directive
 	selected_data="$( printf "%s" "$selected_data" | sed 1d )"
 
+}
+
+print_data () {
 	if [ "$show_link_only" -eq 1 ] ; then
 		printf "%s\n" "$selected_urls"
 		exit
 	fi
+}
 
+get_video_format () {
 	# select format if flag given
 	if [ $show_format -eq 1 ]; then 
 		YTFZF_PREF="$(youtube-dl -F "$(printf "$selected_urls" | sed 1q)" | sed '1,3d' | sed '1!G; h; $!d' |\
@@ -699,6 +701,7 @@ EOF
 		[ -z "$YTFZF_PREF"  ] && exit;
 	fi
 }
+
 play_url () {
 	#> output the current track to current file before playing
 	[ "$show_link_only" -eq 0 ] && printf "Opening Player: %s\n" "$YTFZF_PLAYER"
@@ -748,7 +751,7 @@ check_if_url () {
 	if { printf "%s" "$1" | grep -q "$url_regex"; } ; then
 		is_url=1
 		selected_urls="$(printf "%s" "$1" | tr ' ' '\n')"
-		scrape=""
+		scrape="url"
 	else
 		is_url=0
 	fi
@@ -796,8 +799,6 @@ update_ytfzf () {
 	rm "$updatefile"
 	exit
 }
-
-
 
 scrape_subscriptions () {
 	while read -r url; do
@@ -1038,11 +1039,22 @@ case "$scrape" in
 	"history")
 		get_history
 		;;
+	"url") 
+	    play_url
+	    exit
+	    ;;
+	*)
+	    printf "\033[31mError: \$scrape set to bad option, set to '$scrape'${c_reset}\n"
+	    exit 1 ;;
+
 esac
 
 
 while true; do
 	user_selection
+	format_user_selection
+	print_data
+	get_video_format
 	play_url
 	save_before_exit
 
