Clean: cleaned up readme and commenting in code

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -1,37 +1,22 @@
 #!/bin/sh
 
-# Tweak these (Defaults)
-# ==============================
-## Maximum characters for result
-title_len=60
+# https://github.com/pystardust/ytfzf
+
+# DEFAULTS
+title_len=60                           # Display length for title and channel name
 channel_len=30
-## History settings
-### 0           : Don't save
-### 1           : save
-save_history=1
+save_history=1                         # 0: history off, 1: history on
 history_file=~/.cache/ytfzf_hst
-## Preferred format
-### ""          : empty , choose best quality video (automatic)
-### "22"        : 720p
-### "18"        : 360p
-### "bestaudio" : Best quality only audio (Good for music)
-preferred_format=""
-### 1           : Shows all formats before proceeding
-show_format="0"
-### If preferred format isn't available then it will default 
-### to automatic ,i.e, is best quality video
-## Player
+preferred_format=""                    # ytdl-format (deafults to auto if format not found)"
+show_format="0"                        # 1: shows all formats before proceeding
 player="mpv"
 player_format="mpv --ytdl-format="
-### Player must support viewing of url 
-### you can use a browser here. 
-# ==============================
+FZF_DEFAULT_OPTS=""                    # reset fzf defaults
 
-# Misc
+# HELPER TEXT
 errinfo () { 
 printf "Check for new versions and report at: https://github.com/pystardust/ytfzf\n"
 }
-
 helpinfo () {
 printf "Usage: %bytfzf %b<search query>%b\n" "\033[1;32m" "\033[1;33m" "\033[0m";
 printf "     -h                    Show this help text\n"; 
@@ -41,18 +26,15 @@ printf "     -m  <search query>    Audio only (for listening to music)\n";
 printf "     -d  <search query>    Download to current directory\n"; 
 printf "     -f  <search query>    Show available formats before proceeding\n";
 }
-
 main=0
-# Dependecies check
+
+# DEP CHECK
 dep_ck () {
 	command -v "$1" 1>/dev/null || { printf "$1 not found. Please install it.\n" ; exit 2; }
 }
-dep_ck "jq"
-dep_ck "youtube-dl"
-dep_ck "mpv"
-dep_ck "fzf"
+dep_ck "jq"; dep_ck "youtube-dl"; dep_ck "mpv"; dep_ck "fzf"
 
-# Options
+# OPT
 while getopts "hmdfDH" opt; do
 	case ${opt} in
 		h) 	helpinfo
@@ -91,26 +73,29 @@ while getopts "hmdfDH" opt; do
 done
 shift $((OPTIND-1)) 
 
-
-# Main
+# MAIN
 [ $main -eq 0 ] && {
+[ -z "$*" ] && { helpinfo ; exit 1; }
 
-	[ -z "$*" ] && { helpinfo ; exit 1; }
-	yt_html="$(curl "https://www.youtube.com/results" -s -G --data-urlencode "search_query=$*" )"
-	[ -z "$yt_html" ] &&  { printf "ERROR[#01]: Couldn't curl website. Please check your network and try again.\n"; errinfo; exit 2;}
+yt_html="$(curl "https://www.youtube.com/results" -s -G --data-urlencode "search_query=$*" )"
+[ -z "$yt_html" ] &&  { 
+	printf "ERROR[#01]: Couldn't curl website. Please check your network and try again.\n"; 
+	errinfo; exit 2; }
 
-	yt_json="$(echo "$yt_html" |sed -n '/var *ytInitialData/,$p' | tr -d '\n' | sed -E 's_^.*var ytInitialData ?=__ ; s_;</script>.*__ ; s/\\L//g ' )"
-	[ -z "$yt_json" ] &&  { printf "ERROR[#02]: Couldn't find data on site.\n\tThis shouldn't have happened.\n\tMaybe Youtube has changed somethings.\n"; errinfo ; exit 2; }
+yt_json="$(echo "$yt_html" |sed -n '/var *ytInitialData/,$p' | tr -d '\n' |\
+	sed -E 's_^.*var ytInitialData ?=__ ; s_;</script>.*__ ; s/\\L//g ' )"
+[ -z "$yt_json" ] &&  { 
+	printf "ERROR[#02]: Couldn't find data on site.\n";
+	errinfo ; exit 2; }
 
-  
+videos_data="$(echo "$yt_json" | jq '..|.videoRenderer?' | sed '/^null$/d' |\
+	jq '.title.runs[0].text,.longBylineText.runs[0].text,.shortViewCountText.simpleText,.lengthText.simpleText,.publishedTimeText.simpleText,.videoId' |\
+	sed 's/^"//;s/"$//;s/\\"//g' | sed -E -n "s/(.{$title_len}).*/\1/;N;s/\n(.{$channel_len}).*/\n\1/;N;N;N;N;s/\n/\t|/g;p" |\
+	column -t  -o "$(printf "\t")" -s "$(printf "\t")" )"
+[ -z "$videos_data" ] &&  { printf "No results found. Try different keywords.\n"; errinfo ; exit 1;}
 
-	videos_data="$(echo "$yt_json" | jq '..|.videoRenderer?' | sed '/^null$/d' |\
-		jq '.title.runs[0].text,.longBylineText.runs[0].text,.shortViewCountText.simpleText,.lengthText.simpleText,.publishedTimeText.simpleText,.videoId'|\
-		sed 's/^"//;s/"$//;s/\\"//g' | sed -E -n "s/(.{$title_len}).*/\1/;N;s/\n(.{$channel_len}).*/\n\1/;N;N;N;N;s/\n/\t|/g;p" | column -t  -o "$(printf "\t")" -s "$(printf "\t")" )"
-	[ -z "$videos_data" ] &&  { printf "No results found. Try different keywords.\n"; errinfo ; exit 1;}
-	selected_data="$(echo "$videos_data" | fzf --delimiter="$(printf "\t")" --nth=1,2 )"
-	url="$(echo "$selected_data" | sed -E 's_.*\|([^|]+) *$_https://www.youtube.com/watch?v=\1_')"
-
+selected_data="$(echo "$videos_data" | fzf --delimiter="$(printf "\t")" --nth=1,2 )"
+url="$(echo "$selected_data" | sed -E 's_.*\|([^|]+) *$_https://www.youtube.com/watch?v=\1_')"
 }
 
 [ -z "$url" ] && exit;
@@ -118,7 +103,7 @@ shift $((OPTIND-1))
 	preferred_format="$(youtube-dl -F "$url" | sed '1,3d' | tac - | fzf | sed -E 's/^([^ ]*) .*/\1/')"
 }
 
-# Action
+# PLAY
 [ -n "$preferred_format" ] && {
 	eval "$player_format""$preferred_format"  "$url" 
 } || { 
