refactor: Better variable names (#136)
* better long-opt names

* update docs

* better conf.sh

* excessive 0s when reseting colors

* better help menu

* update --previews -> --preview-side, printf -> print_error

* revert download thumbnails

* removed color from help

Co-authored-by: Euro <no>

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -12,8 +12,8 @@ YTFZF_VERSION="1.0.1"
 
 
 #>reading the config file
-config_dir="$HOME/.config/ytfzf"
-config_file="$config_dir/conf.sh"
+config_dir="${YTFZF_CONFIG_DIR-$HOME/.config/ytfzf}"
+config_file="${YTFZF_CONFIG_FILE-$config_dir/conf.sh}"
 tmp_video_data_file="/tmp/ytfzf-subdata"
 printf "" > "$tmp_video_data_file"
 #source config file if exists
@@ -126,78 +126,91 @@ dep_ck "jq" "youtube-dl";
 ############################
 #       Help Texts         #
 ############################
-helpinfo () {
-printf "Usage: %bytfzf [OPTIONS] %b<search-query>%b\n" "\033[1;32m" "\033[1;33m" "\033[0m";
-printf "  OPTIONS:\n"
-printf "     -h, --help                           Show this help text\n";
-printf "     -v, --version                        -v for ytfzf's version\n";
-printf "                                          --version for ytfzf + dependency's versions\n"
-printf "     -t, --thumbnails                     Show thumbnails (requires ueberzug)\n";
-printf "                                          Doesn't work with -H -D\n";
-printf "     -D, --ext-menu                       Use external menu(default dmenu) instead of fzf \n";
-printf "     -H, --choose-from-history            Choose from history \n";
-printf "     -x, --clear-history                  Delete history\n";
-printf "     -m, --audio-only   <search-query>    Audio only (for music)\n";
-printf "     -d, --download     <search-query>    Download to current directory\n";
-printf "     -f                 <search-query>    Show available formats before proceeding\n";
-printf "     -a, --auto-play    <search-query>    Auto play the first result, no selector\n";
-printf "     -r  --random-play  <search-query>    Auto play a random result, no selector\n";
-printf "     -A, --select-all   <search-query>    Selects all results\n";
-printf "     -n, --video-count= <video-count>     To specify number of videos to select with -a, -r\n";
-printf "     -l, --loop         <search-query>    Loop: prompt selector again after video ends\n";
-printf "     -s                 <search-query>    After the video ends make another search \n";
-printf "     -L, --link-only    <search-query>    Prints the selected URL only, helpful for scripting\n";
-printf "\n";
-printf "  Subscriptions: to add a channel to subscptions, copy the channel's video page url\n";
-printf "                 and add it to ~/.config/ytfzf/subscriptions. Each url must be on a new line\n";
-printf "     -S,  --subs                          Get the latest 10 videos from subscriptions\n"
-printf "     --subs=<number>                      Get the latest <number> of videos from subscriptions\n";
-printf "     --fancy-subs=                        whether or not to show ------channel------ in subscriptions (must be 1 or 0)\n";
-printf "\n"
-printf "     --previews=        <left/right>      the side of the screen to show thumbnails\n";
-printf "     --upload-time=     <time-range>      Time range can be one of, \n";
-printf "                                          last-hour, today, this-week, this-month, this-year\n"
-printf "                                          Filters can go directly: --today\n";
-printf "     --upload-sort=     <sort-filter>     The filter to sort the videos can be one of\n";
-printf "                                          upload-date, view-count, rating\n";
-printf "                                          Filters can go directly: --upload-date\n";
-printf "     --filter-id=       <filter>          The id of the filter to use for video results\n";
-printf "         A filter id can be found by going to Youtube searching, filtering how you want\n";
-printf "         Then taking the value of the &sp= part of the url\n";
-printf "         Filters may not work especially when the filter sorts for non-videos\n";
-printf "         In addition this overrides any filter provided through options\n";
-printf "         Example: \033[1mytfzf --filter-id=EgJAAQ minecraft\033[000m\n";
-printf "         This will filter by livestream\n";
-printf "\n";
-printf "     --update                             clones the latest stable commit and installs it\n";
-printf "                                          on Arch ytfzf is available in the AUR\n";
-printf "     --update-unstable                    gets the latest commit and installs it (--update is safer)\n";
-printf "\n";
-printf "  Use - instead of <search-query> for stdin\n";
-printf "\n"
-printf "  Option usage:\n"
-printf "     ytfzf -fDH                           to show history using external \n"
-printf "                                          menu and show formats\n"
-printf "     ytfzf -fD --choose-from-history      same as above\n"
-printf "\n"
-printf "  Defaults can be modified through ENV variables or the config file\n";
-printf "  the default config file can be found at https://github.com/pystardust/ytfzf/blob/master/docs/conf.sh\n";
-printf "  Defaults:\n";
-printf "     YTFZF_HIST=1                          0 : off history\n";
-printf "     YTFZF_CACHE=~/.cache/ytfzf\n";
-printf "     YTFZF_LOOP=0                          1 : loop the selection prompt\n";
-printf "     YTFZF_PREF=''                         22: 720p,  18: 360p\n";
-printf "     YTFZF_CUR=1                           For status bar bodules\n";
-printf "     YTFZF_EXTMENU=' dmenu -i -l 30'\n";
-printf "  To use rofi\n";
-printf "     YTFZF_EXTMENU=' rofi -dmenu -fuzzy -width 1500'\n";
-printf "     YTFZF_ENABLE_FZF_DEFAULT_OPTS=0       1 : fzf will use FZF_DEFAULT_OPTS\n";
-printf "\n";
+
+basic_helpinfo () {
+    printf "Usage: ytfzf [OPTIONS...] <search-query>\n";
+    printf "  OPTIONS:\n" 
+    printf "     -h, --help                             Show this help text\n";
+    printf "     -v, --version                          -v for ytfzf's version\n";
+    printf "                                            --version for ytfzf + dependency's versions\n"
+    printf "     -t, --thumbnails                       Show thumbnails (requires ueberzug)\n";
+    printf "                                            Doesn't work with -H -D\n";
+    printf "     -D, --ext-menu                         Use external menu(default dmenu) instead of fzf \n";
+    printf "     -H, --choose-from-history              Choose from history \n";
+    printf "     -x, --clear-history                    Delete history\n";
+    printf "     -m, --audio-only     <search-query>    Audio only (for music)\n";
+    printf "     -d, --download       <search-query>    Download to current directory\n";
+    printf "     -f                   <search-query>    Show available formats before proceeding\n";
+    printf "     -a, --auto-select    <search-query>    Auto play the first result, no selector\n";
+    printf "     -r  --random-select  <search-query>    Auto play a random result, no selector\n";
+    printf "     -A, --select-all     <search-query>    Selects all results\n";
+    printf "     -n, --link-count=    <link-count>      To specify number of videos to select with -a, -r\n";
+    printf "     -l, --loop           <search-query>    Loop: prompt selector again after video ends\n";
+    printf "     -s, --search-again   <search-query>    After the video ends make another search \n";
+    printf "     -L, --link-only      <search-query>    Prints the selected URL only, helpful for scripting\n";
+    printf "     --preview-side=      <left/right/top/bottom>    the side of the screen to show thumbnails\n";
+    printf "\n"
+    printf "  Use - instead of <search-query> for stdin\n" 
+    printf "\n";
+    printf "  Option usage:\n" 
+    printf "     ytfzf -fDH                           to show history using external \n"
+    printf "                                          menu and show formats\n"
+    printf "     ytfzf -fD --choose-from-history      same as above\n"
+    printf "\n"
 }
+
+all_help_info () {
+    basic_helpinfo
+    printf "  Subscriptions: to add a channel to subscptions, copy the channel's video page url\n" 
+    printf "                 and add it to ~/.config/ytfzf/subscriptions. Each url must be on a new line\n";
+    printf "     -S,  --subs                          Get the latest 10 videos from subscriptions\n"
+    printf "     --subs=<number>                      Get the latest <number> of videos from subscriptions\n";
+    printf "     --fancy-subs=                        whether or not to show ------channel------ in subscriptions (must be 1 or 0)\n";
+    printf "\n"
+    printf "  Filters: different ways to filter videos in search\n" 
+    printf "     --upload-time=     <time-range>      Time range can be one of, \n";
+    printf "                                          last-hour, today, this-week, this-month, this-year\n"
+    printf "                                          Filters can go directly: --today\n";
+    printf "     --upload-sort=     <sort-filter>     The filter to sort the videos can be one of\n";
+    printf "                                          upload-date, view-count, rating\n";
+    printf "                                          Filters can go directly: --upload-date\n";
+    printf "     --filter-id=       <filter>          The id of the filter to use for video results\n";
+    printf "         A filter id can be found by going to Youtube searching, filtering how you want\n";
+    printf "         Then taking the value of the &sp= part of the url\n";
+    printf "         Filters may not work especially when the filter sorts for non-videos\n";
+    printf "         In addition this overrides any filter provided through options\n";
+    printf "         Example: \033[1mytfzf --filter-id=EgJAAQ minecraft\033[0m\n";
+    printf "         This will filter by livestream\n";
+    printf "\n";
+    printf "  Update:\n" 
+    printf "     --update                             clones the latest stable commit and installs it\n";
+    printf "                                          on Arch ytfzf is available in the AUR\n";
+    printf "     --update-unstable                    gets the latest commit and installs it (--update is safer)\n";
+    printf "\n";
+    printf "\n"
+    printf "  Defaults can be modified through ENV variables or the config file\n";
+    printf "  the default config file can be found at https://github.com/pystardust/ytfzf/blob/master/docs/conf.sh%b\n"
+    printf "\n"
+    printf "  Environment Variables:\n" 
+    printf "     YTFZF_HIST=1                          0 : off history\n";
+    printf "     YTFZF_CACHE=~/.cache/ytfzf\n";
+    printf "     YTFZF_LOOP=0                          1 : loop the selection prompt\n";
+    printf "     YTFZF_PREF=''                         22: 720p,  18: 360p\n";
+    printf "     YTFZF_CUR=1                           For status bar bodules\n";
+    printf "     YTFZF_ENABLE_FZF_DEFAULT_OPTS=0       1 : fzf will use FZF_DEFAULT_OPTS\n";
+    printf "     YTFZF_CONFIG_DIR='~/.config/ytfzf'    The directory to store config files\n";
+    printf "     YTFZF_CONFIG_FILE='\$YTFZF_CONFIG_DIR/conf.sh'   The configuration file\n";
+    printf "     YTFZF_EXTMENU=' dmenu -i -l 30'\n";
+    printf "  To use rofi\n";
+    printf "     YTFZF_EXTMENU=' rofi -dmenu -fuzzy -width 1500'\n";
+    printf "\n";
+}
+
 usageinfo () {
     printf "Usage: %bytfzf %b<search query>%b\n" "\033[1;32m" "\033[1;33m" "\033[0m";
     printf "     'ytfzf -h' for more information\n";
 }
+
 print_error () {
     printf "$*"
     printf "Check for new versions and report at: https://github.com/pystardust/ytfzf\n"
@@ -395,7 +408,7 @@ download_thumbnails () {
 		else
 			name="$line"
 			{
-				curl -s "$url" > "$thumb_dir/$name.png"
+			    curl -s "$url" > "$thumb_dir/$name.png"
 			} &
 		fi
 		i=$((i + 1))
@@ -486,7 +499,7 @@ scrape_channel () {
 	yt_html="$(get_yt_html "$*")"
 
 	if [ -z "$yt_html" ]; then
-	        print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
+	        print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[0m\n"
 	        exit 1
 	fi
 
@@ -548,7 +561,7 @@ scrape_yt () {
 
 	yt_html="$(get_yt_html "https://www.youtube.com/results" "$*")"
 	if [ -z "$yt_html" ]; then
-		print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
+		print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[0m\n"
 		exit 1
 	fi
 
@@ -556,7 +569,7 @@ scrape_yt () {
 
 	#if the data couldn't be found
 	if [ -z "$yt_json" ]; then
-		print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[000m\n"
+		print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[0m\n"
 		exit 1
 	fi
 
@@ -680,7 +693,7 @@ play_url () {
 		[ 4 -eq $? ] || eval "$YTFZF_PLAYER" "$player_urls"
                      # Ctr-C in MPV results in a return code of 4
 	} || {
-		print_error "\033[31mERROR[#03]: Couldn't play the video/audio using the current player: ${YTFZF_PLAYER}\n\t\033[000mTry updating youtube-dl\n"; save_before_exit ; exit 1;
+		print_error "\033[31mERROR[#03]: Couldn't play the video/audio using the current player: ${YTFZF_PLAYER}\n\t\033[0mTry updating youtube-dl\n"; save_before_exit ; exit 1;
 	}
 }
 #> Checks if other sessions are running, if not then deletes thumbnails
@@ -737,7 +750,7 @@ clear_history () {
 		echo "" > "$history_file"
 		printf "History has been cleared\n"
 	else
-		printf "\033[31mHistory file not found, history not cleared\033[000m\n"
+		printf "\033[31mHistory file not found, history not cleared\033[0m\n"
 		exit 1
 	fi
 }
@@ -788,7 +801,7 @@ is_non_number () {
 bad_opt_arg () {
 	opt="$1"
 	arg="$2"
-	printf "%s\n" "$opt requires a numeric arg, but was given \"$OPTARG\""
+	printf "%s\n" "$opt requires a numeric arg, but was given \"$arg\""
 	exit 2
 }
 
@@ -798,9 +811,12 @@ parse_long_opt () {
 	#if the option has a short version it calls this function with the opt as the shortopt
 	case "${opt}" in
 	        help) parse_opt "h" ;;
+		help-all) 
+		    all_help_info 
+		    exit ;;
 
-		ext-menu) parse_opt "D" ;;
-		ext-menu=*)
+		is-ext-menu) parse_opt "D" ;;
+		is-ext-menu=*)
 		    parse_opt "D" "${opt#*=}"
 		    is_non_number "$is_ext_menu" && bad_opt_arg "--ext-menu=" "$is_ext_menu" ;;
 
@@ -810,8 +826,8 @@ parse_long_opt () {
 
 		clear-history) parse_opt "x" ;;
 
-		search) parse_opt "s" ;;
-		search=*)
+		search-again) parse_opt "s" ;;
+		search-again=*) 
 		    parse_opt "s" "${opt#*=}"
 		    is_non_number "$search_again" && bad_opt_arg "--search=" "$search_again" ;;
 
@@ -820,22 +836,22 @@ parse_long_opt () {
 		    parse_opt "l" "${opt#*=}"
 		    is_non_number "$YTFZF_LOOP" && bad_opt_arg "--loop=" "$YTFZF_LOOP" ;;
 
-		thumbnails) parse_opt "t" ;;
-		thumbnails=*)
+		show-thumbnails) parse_opt "t" ;;
+		show-thumbnails=*)
 		    parse_opt "t" "${opt#*=}"
 		    is_non_number "$show_thumbnails" && bad_opt_arg "--thumbnails=" "$show_thumbnails" ;;
 
-		link-only) parse_opt "L" ;;
-		link-only=*)
+		show-link-only) parse_opt "L" ;;
+		show-link-only=*)
 		    parse_opt "L" "${opt#*=}"
 		    is_non_number "$show_link_only" && bad_opt_arg "--link-only=" "$show_link_only" ;;
 
-		video-count=*) parse_opt "n" "${opt#*=}" ;;
+		link-count=*) parse_opt "n" "${opt#*=}" ;;
 
 		audio-only) parse_opt "m" ;;
 
-		auto-play) parse_opt "a" ;;
-		auto-play=*)
+		auto-select) parse_opt "a" ;;
+		auto-select=*) 
 		    parse_opt "a" "${opt#*=}"
 		    is_non_number "$auto_select" && bad_opt_arg "--auto-play=" "$auto_select" ;;
 
@@ -844,8 +860,8 @@ parse_long_opt () {
 		    parse_opt "A" "${opt#*=}"
 		    is_non_number "$select_all" && bad_opt_arg "--select-all=" "$select_all" ;;
 
-		random-play) parse_opt "r" ;;
-		random-play=*)
+		random-select) parse_opt "r" ;;
+		random-select=*) 
 		    parse_opt "r" "${opt#*=}"
 		    is_non_number "$random_select" && bad_opt_arg "--random-play=" "$random_select" ;;
 
@@ -863,7 +879,7 @@ parse_long_opt () {
 
 		filter-id=*|sp=*) sp="${opt#*=}" ;;
 
-		previews=*) export PREVIEW_SIDE="${opt#*=}" ;;
+		preview-side=*) export PREVIEW_SIDE="${opt#*=}" ;;
 
 		update) update_ytfzf "master" ;;
 		update-unstable) update_ytfzf "development" ;;
@@ -879,9 +895,9 @@ parse_long_opt () {
 		fancy-subs=*) fancy_subscriptions_menu="${opt#*=}" ;;
 
 		version)
-		    printf "\033[1mytfzf:\033[000m %s\n" "$YTFZF_VERSION"
-		    printf "\033[1myoutube-dl:\033[00m %s\n" "$(youtube-dl --version)"
-		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[000m %s\n" "$(fzf --version)"
+		    printf "\033[1mytfzf:\033[0m %s\n" "$YTFZF_VERSION"
+		    printf "\033[1myoutube-dl:\033[0m %s\n" "$(youtube-dl --version)"
+		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[0m %s\n" "$(fzf --version)"
 		    exit ;;
 
 		*)
@@ -899,7 +915,8 @@ parse_opt () {
 		#Long options
 		-)	parse_long_opt "$OPTARG" ;;
 		#Short options
-		h) 	helpinfo
+		h) 	basic_helpinfo
+			printf "type --help-all for more info\n"
 			exit ;;
 
 		D) 	is_ext_menu="${OPTARG:-1}" ;;
@@ -957,14 +974,14 @@ shift $((OPTIND-1))
 #if both are true, it defaults to using fzf, and if fzf isnt installed it will throw an error
 #so print this error instead and set $show_thumbnails to 0
 if [ $is_ext_menu -eq 1 -a $show_thumbnails -eq 1 ]; then
-	printf "\033[31mCurrently thumbnails do not work in external menus\033[000m\n"
+	printf "\033[31mCurrently thumbnails do not work in external menus\033[0m\n"
 	show_thumbnails=0
 fi
 
 #if stdin is given and no input (including -) is given, throw error
 #also make sure its not reading from ext_menu
 if [ ! -t 0 ] && [ -z "$*" ] && [ $is_ext_menu -eq 0 ]; then
-	printf "\033[31mERROR[#04]: Use - when reading from stdin\033[000m\n"
+	print_error "\033[31mERROR[#04]: Use - when reading from stdin\033[0m\n"
 	exit 2
 #read stdin if given
 elif [ "$*" = "-" ]; then
