Better help on no input

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -70,6 +70,10 @@ while getopts "hmdfH" opt; do
 				main=1
 				} || { printf "History is not enabled. Please enable it to use this option -H.\n";}
 			;;
+		*)
+			printf "Option not found!\n"
+			helpinfo 
+			exit 2;
 	esac
 done
 shift $((OPTIND-1)) 
@@ -78,7 +82,7 @@ shift $((OPTIND-1))
 # Main
 [ $main -eq 0 ] && {
 
-	[ -z "$*" ] && { printf "Usage: %bytfzf %b<search query>%b\n" "\033[1;32m" "\033[1;33m" "\033[0m"; exit 1; }
+	[ -z "$*" ] && { helpinfo ; exit 1; }
 	yt_html="$(curl "https://www.youtube.com/results" -s -G --data-urlencode "search_query=$*" )"
 	[ -z "$yt_html" ] &&  { printf "ERROR[#01]: Couldn't curl website. Please check your network and try again.\n"; errinfo; exit 2;}
 
