--update

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -122,6 +122,9 @@ printf "                   Filters may not work especially when the filter sorts
 printf "                   In addition this overrides any filter provided through options\n";
 printf "                   Example: \033[1mytfzf --filter-id=EgJAAQ minecraft\033[000m\n";
 printf "                   This will filter by livestream\n";
+printf "\n";
+printf "     --update                             clones the latest commit and installs it\n";
+printf "                   on Arch ytfzf is available in the AUR\n";
 printf "  Use - instead of <search-query> for stdin\n";
 printf "\n"
 printf "  Option usage:\n"
@@ -615,6 +618,23 @@ parse_opt () {
 				rating) sort_by_filter="rating" ;;
 
 				filter-id=*|sp=*) sp="${OPTARG#*=}" ;;
+
+				update) 
+				    #check for root privileges
+				    if [ $(id -u) -ne 0 ]; then
+					printf "Missing root privileges, run again as root\n"
+					exit 126
+				    fi
+				    #clone repo into temp directory
+				    git clone https://github.com/pystardust/ytfzf .clone-ytfzf-tmp
+				    #go into directory and install
+				    cd .clone-ytfzf-tmp
+				    make install
+				    #leave directory and remove the temp directory
+				    cd ..
+				    rm -r .clone-ytfzf-tmp
+				    exit
+				    ;;
 
 				version) 
 				    printf "ytfzf: $YTFZF_VERSION\n"
