subscriptions

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -53,6 +53,7 @@ config_file="$config_dir/conf.sh"
 history_file="$YTFZF_CACHE/ytfzf_hst"
 current_file="$YTFZF_CACHE/ytfzf_cur"
 thumb_dir="$YTFZF_CACHE/thumb"
+subscriptions_file="${subscriptions_file-$config_dir/subscriptions.json}"
 
 #> stores the pid of running ytfzf sessions
 pid_file="$YTFZF_CACHE/.pid"
@@ -65,6 +66,8 @@ thumb_dir="$YTFZF_CACHE/thumb"
 search_prompt="${search_prompt-Search Youtube: }"
 #used when getting the html from youtube
 useragent=${useragent-'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36'}
+#instead of just a list of videos, add some titles
+fancy_subscriptions_menu=${fancy_subscriptions_menu-1}
 
 #Opt variables (can also be set in config)
 #use $YTFZF_EXT_MENU (same as -D)
@@ -87,6 +90,8 @@ link_count=${link_count-1}
 search_again=${search_again-0}
 #filter id used when searching
 sp="${sp-}"
+#scrape subscriptions.json file instead of a search query
+get_subscriptions=0
 
 #ueberzug related variables
 #the side where thumbnails are shown
@@ -127,13 +132,15 @@ printf "                                          Doesn't work with -H -D\n";
 printf "     -D, --ext-menu                       Use external menu(default dmenu) instead of fzf \n";
 printf "     -H, --choose-from-history            Choose from history \n";
 printf "     -x, --clear-history                  Delete history\n";
+printf "     -S                                   Get the latest videos from subscriptions\n"
 printf "     -m, --audio-only   <search-query>    Audio only (for music)\n";
 printf "     -d, --download     <search-query>    Download to current directory\n";
 printf "     -f                 <search-query>    Show available formats before proceeding\n";
 printf "     -a, --auto-play    <search-query>    Auto play the first result, no selector\n";
 printf "     -r  --random-play  <search-query>    Auto play a random result, no selector\n";
 printf "     -A, --select-all   <search-query>    Selects all results\n";
-printf "     -n, --video-count= <video-count>     To specify number of videos to select with -a or -r\n";
+printf "     -n, --video-count= <video-count>     To specify number of videos to select with -a, -r or -S\n";
+printf "                   if -n is given with both -a/-r and -S, it will apply to both"
 printf "     -l, --loop         <search-query>    Loop: prompt selector again after video ends\n";
 printf "     -s                 <search-query>    After the video ends make another search \n";
 printf "     -L, --link-only    <search-query>    Prints the selected URL only, helpful for scripting\n";
@@ -305,7 +312,7 @@ stop_ueberzug () {
 }
 
 preview_img () {
-	shorturl="$(echo "$@" | sed -E -e 's_.*\|([^|]+) *$_\1_')"
+	shorturl="$(echo "$*" | sed -E -e 's_^.*\|__')"
 
 	thumb_width=$WIDTH
 	thumb_height=$((HEIGHT - 2))
@@ -327,13 +334,13 @@ preview_img () {
 	esac
 
 	# In fzf the cols and lines are those of the preview pane
-	IMAGE="$thumb_dir/$shorturl.png"
+	IMAGE="$thumb_dir/${shorturl%% *}.png"
 	{   printf '{ "action": "add", "identifier": "%s", "path": "%s",' "$ID" "$IMAGE"
 	    printf '"x": %d, "y": %d, "scaler": "fit_contain",' $thumb_x $thumb_y
 	    printf '"width": %d, "height": %d }\n' "$thumb_width" "$thumb_height"
 	} > "$FIFO" 
-	echo "$@" |  tr -d '|' | sed "s/ *""$(printf '\t')""/""$(printf '\t')""/g" | awk -F"$(printf '\t')" \
-	'{ printf "\n%s\nChannel: %s\nViews: %s\nDuration: %s\nUploaded %s\n",$1,$2,$4,$3,$5}'
+	echo "$*" |  tr -d '|' | sed "s/ *""$(printf '\t')""/""$(printf '\t')""/g" | awk -F"$(printf '\t')" \
+	'{ printf "\n%s\nChannel: %s\nViews: %s\nDuration: %s\nUploaded %s\n",$1,$2,$3,$4,$5}'
 }
 
 
@@ -343,18 +350,22 @@ preview_img () {
 
 download_thumbnails () {
 	#scrapes the urls of the thumbnails of the videos
-	thumb_urls="$(printf "%s" "$videos_json" |\
-		jq  '.thumbnail.thumbnails[0].url,.videoId' )"
 
-	[ $show_link_only -eq 0 ] && printf "Downloading Thumbnails.."
+	[ -z "$1" ] && thumb_urls="$(printf "%s" "$videos_json" |\
+		jq  -r '.[]|(.thumbs,.videoID)' )"
+
+	[ $show_link_only -eq 0 ] && printf "Downloading Thumbnails"
     
 	i=0
 	while read line; do
 		if [ $((i % 2)) -eq 0 ]; then
 			url="$(echo $line | sed -E 's/^"//;s/\.png.*/\.png/')" 
 		else
-			name="$(echo "$line" | tr -d '"')"
-			{ curl -s "$url" > "$thumb_dir/$name.png" && [ $show_link_only -eq 0 ] && printf "."; } &
+			name="$line"
+			{ 
+				curl -s "$url" > "$thumb_dir/$name.png" 
+				[ $show_link_only -eq 0 ] && printf "."; 
+			} &
 		fi
 		i=$((i + 1))
 	done << EOF
@@ -405,6 +416,111 @@ get_sp_filter () {
 		sp="$filter_id"
 	fi
 }
+
+get_yt_json () {
+	#youtube has a bunch of data relating to videos in a json format, this scrapes that
+	yt_json="$(printf "%s" "$yt_html" | sed -n '/var *ytInitialData/,$p' | tr -d '\n' |\
+        sed -E ' s_^.*var ytInitialData ?=__ ; s_;</script>.*__ ;')"
+}
+
+get_yt_html () {
+    link="$1"
+    query="$2"
+    yt_html="$(
+	curl "$link" -s \
+	  -G --data-urlencode "search_query=$query" \
+	  -G --data-urlencode "sp=$sp" \
+	  -H 'authority: www.youtube.com' \
+	  -H "user-agent: $useragent" \
+	  -H 'accept-language: en-US,en;q=0.9' \
+	  --compressed
+    )"
+    if [ -z "$yt_html" ]; then
+	    print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
+	    exit 1 
+    fi
+}
+
+get_video_data () {
+	#in that list this finds the title, channel, view count, video length, video upload date, and the video id/url
+	videos_data="$(printf "%s" "$videos_json" |\
+		jq -r '.[]| (
+			.title,
+			.channel,
+			.views,
+			.duration,
+			.date,
+			.videoID
+			)' | sed "N;N;N;N;N;s/\n/""$(printf '\t')""\|/g")"
+	    #if there aren't videos
+	    [ -z "$videos_data" ] &&  { printf "No results found. Try different keywords.\n"; exit 1;}
+}
+
+scrape_subscriptions () {
+	if [ ! -e "$subscriptions_file" ]; then
+		printf "\033[31mERROR[#05]: \"$subscriptions_file\" not found\033[000m\n"
+		exit 1
+	fi
+	#get the subscriptions json
+	subscriptions="$(cat "$subscriptions_file" | jq)"
+	#get each channel link
+	channel_links="$(echo "$subscriptions" | jq '.[].link' | tr '"' ' ')"
+	for link in $channel_links; do
+	    echo "Fetching $link" 
+	    get_yt_html "$link"
+	    #gets the channel name from title of page
+	    channel_name="$(echo "$yt_html" | grep -o '<title>.*</title>' | sed 's/<\/\?title>//g' | sed 's/ - YouTube//')"
+	    #gets json of videos
+	    get_yt_json
+	    #gets a list of videos
+	    videos_json="$(printf "%s" "$yt_json" |\
+	    jq '[ .contents | ..|.gridVideoRenderer? | 
+	    select(. !=null) | 
+		{
+			title: .title.runs[0].text,
+			channel:"'"$channel_name"'",
+			duration:.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer.text.simpleText,
+			views: .shortViewCountText.simpleText,
+			date: .publishedTimeText.simpleText,
+			videoID: .videoId,
+			thumbs: .thumbnail.thumbnails[0].url,
+		}
+	    ]')"
+
+	    #gets new videos and thumbnails
+	    #if select all is on, keep all the results
+
+	    if [ $fancy_subscriptions_menu -eq 1 ]; then
+		temp_videos_data="${videos_data-------------Subscriptions------------}
+------------$channel_name------------"
+	    else
+		temp_videos_data="$videos_data"
+	    fi
+
+	    get_video_data
+
+	    #if not select all, or random select, get only the needed videos
+	    if [ $select_all -eq 0 -a $random_select -eq 0 ]; then
+		videos_data="$(echo "$videos_data" | sed ${link_count}q)"
+		videos_json="$(echo "$videos_json" | jq '.[0:'$link_count']')"
+	    fi
+
+	    #run user selection on the currently found urls that way it runs -a, etc.. on each subscription instead of once
+	    [ $auto_select -eq 1 -o $random_select -eq 1 -o $select_all -eq 1 ] && user_selection
+	    
+	    new_thumb_urls="$(printf "%s" "$videos_json" | jq -r '.[]|(.thumbs,.videoID)')"
+	    #adds new thumbnails to old thumbnails
+	    thumb_urls="$new_thumb_urls
+$thumb_urls"
+	    #adds the new videos to the previously gotten videos
+	    [ -n "$temp_videos_data" ] && videos_data="$(printf "%s\n" "$temp_videos_data" "$videos_data")"
+
+	    #gets all subscription urls before playing them in video player and before showing links_only
+	    subscription_urls="$subscription_urls\n$urls"
+	done
+	[ $show_link_only -eq 1 ] && echo "$(echo "$subscription_urls" | sed 1d)" && exit
+	[ $show_thumbnails -eq 1 ] && download_thumbnails "$thumb_urls"
+}
 scrape_yt () {
 	# needs search_query
 	## Scrape data and store video information in videos_data ( and thumbnails download)
@@ -419,24 +535,9 @@ scrape_yt () {
 		sp="${sp%%%*}"
 	fi
 
-	yt_html="$(
-	curl 'https://www.youtube.com/results' -s \
-	  -G --data-urlencode "search_query=$*" \
-	  -G --data-urlencode "sp=$sp" \
-	  -H 'authority: www.youtube.com' \
-	  -H "user-agent: $useragent" \
-	  -H 'accept-language: en-US,en;q=0.9' \
-	  --compressed
-	)"
-	#if there's no html
-	if [ -z "$yt_html" ]; then
-		print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
-		exit 1 
-	fi
+	get_yt_html "https://www.youtube.com/results" "$*"
 
-	#youtube has a bunch of data relating to videos in a json format, this scrapes that
-	yt_json="$(printf "%s" "$yt_html" | sed -n '/var *ytInitialData/,$p' | tr -d '\n' |\
-        sed -E ' s_^.*var ytInitialData ?=__ ; s_;</script>.*__ ;')"
+	get_yt_json
 
 	#if the data couldn't be found
 	if [ -z "$yt_json" ]; then  
@@ -445,14 +546,21 @@ scrape_yt () {
 	fi
 
 	#gets a list of videos
-	videos_json="$(printf "%s" "$yt_json" | jq '..|.videoRenderer?' | sed '/^null$/d')"
-	#in that list this finds the title, channel, view count, video length, video upload date, and the video id/url
-	videos_data="$( printf "%s" "$videos_json" |\
-		jq  '.title.runs[0].text,.longBylineText.runs[0].text,.shortViewCountText.simpleText,.lengthText.simpleText,.publishedTimeText.simpleText,.videoId' |\
-		sed 's/^"//;s/"$//;s/\\"//g' | sed -E -n ";N;N;N;N;N;s/\n/""$(printf '\t')""\|/g;p")"
+	videos_json="$(printf "%s" "$yt_json" | jq '[ .contents| 
+	..|.videoRenderer? | 
+	select(. !=null) | 
+		{
+			title: .title.runs[0].text,
+			channel: .longBylineText.runs[0].text,
+			duration:.lengthText.simpleText,
+			views: .shortViewCountText.simpleText,
+			date: .publishedTimeText.simpleText,
+			videoID: .videoId,
+			thumbs: .thumbnail.thumbnails[0].url
+		}
+	]')"
 
-	#if there aren't videos
-	[ -z "$videos_data" ] &&  { printf "No results found. Try different keywords.\n"; exit 1;}
+	get_video_data
 
 	[ $show_thumbnails -eq 1 ] && download_thumbnails
 }
@@ -519,9 +627,10 @@ user_selection () {
 EOF
 	urls="$( printf "$urls" | sed 1d )"
 	#sometimes % shows up in selected data, could throw an error if it's an invalid directive
-	selected_data="$( printf "%s" "$selected_data" | sed 1d )"
+	selected_data="$( printf "$selected_data" | sed 1d )"
 
-	if [ $show_link_only -eq 1 ] ; then
+	#if getting subscriptions, this will echo urls too early
+	if [ $show_link_only -eq 1 -a $get_subscriptions -eq 0 ] ; then
 		echo "$urls"
 		exit
 	fi
@@ -536,6 +645,9 @@ EOF
 play_url () {
 	#> output the current track to current file before playing
 	[ $YTFZF_CUR -eq 1 ] && printf "$selected_data" > "$current_file" ;
+
+	#if the subscription_urls have word characters, then use them as the urls
+	[ -n "$(echo "$subscription_urls" | grep -o '\w')" ] && urls="$(echo "$subscription_urls" | sed 1d)"
 
 	#> The urls are quoted and placed one after the other for mpv to read
 	player_urls="\"$(printf "$urls" | awk  'ORS="\" \"" { print }' | sed 's/"$//' )"
@@ -720,6 +832,8 @@ parse_opt () {
 
 		s)	search_again=1 ;;
 
+		S)	get_subscriptions=1 ;;
+
 		l) 	YTFZF_LOOP=1 ;;
 
 		t) 	show_thumbnails=1 ;;
@@ -742,13 +856,14 @@ parse_opt () {
 	esac
 }
 
-while getopts "LhDmdfxHaArltsvn:U:-:" opt; do
+while getopts "LhDmdfxHaArltSsvn:U:-:" opt; do
     parse_opt "$opt" "$OPTARG"
 done
 shift $((OPTIND-1))
 
 #if stdin is given and no input (including -) is given, throw error
-if [ ! -t 0 -a -z "$*" ]; then
+#also make sure it's not reading from ext_menu
+if [ ! -t 0 -a -z "$*" -a $is_ext_menu -eq 0 ]; then
 	printf "\033[31mERROR[#04]: Use - when reading from stdin\033[000m\n"
 	exit 1
 #read stdin if given
@@ -768,7 +883,12 @@ check_if_url "${search_query:=$*}"
 format_menu 
 
 #call scrape function
-if [ $scrape -eq 1 ]; then 
+if [ $get_subscriptions -eq 1 ]; then
+	if [ $auto_select -eq 1 -o $random_select -eq 1 -o $select_all -eq 1 ]; then
+	    fancy_subscriptions_menu=0
+	fi
+	scrape_subscriptions
+elif [ $scrape -eq 1 ]; then 
 	get_search_query
 	scrape_yt "$search_query"
 fi
