feat: swayimg-hyprland thumbnail viewer

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -3,7 +3,7 @@
 
 # versioning system:
 # major.minor.bugs
-YTFZF_VERSION="2.5.3.rc-1"
+YTFZF_VERSION="git-1777.0cd64a7"
 
 # Scraping: query -> video json
 # User Interface: video json -> user selection -> ID
@@ -584,6 +584,7 @@ load_thumbnail_viewer () {
     case "$_thumbnail_viewer" in
            # these are special cases, where they are not themselves commands
            chafa-16|chafa|chafa-tty|catimg|catimg-256|imv|ueberzug|kitty|swayimg|mpv) thumbnail_viewer="$_thumbnail_viewer" ; true ;;
+           swayimg-hyprland) print_warning "swayimg-hyprland thumbnail viewer may mess up any rules you have for swayimg\n"; thumbnail_viewer="$_thumbnail_viewer" ;;
            ./*|/*|../*|~/*) thumbnail_viewer="$_thumbnail_viewer"; false ;;
            *)
                    if [ -f "${YTFZF_THUMBNAIL_VIEWERS_DIR}/${_thumbnail_viewer}" ]; then
@@ -1839,7 +1840,7 @@ preview_start () {
 			ueberzug layer --parser json < "$UEBERZUG_FIFO"  > "$thumbnail_debug_log" 2>&1 &
 			exec 3> "$UEBERZUG_FIFO" # to keep the fifo open 
 			;;
-		chafa|chafa-16|chafa-tty|catimg|catimg-256|swayimg) : ;;
+		chafa|chafa-16|chafa-tty|catimg|catimg-256|swayimg|swayimg-hyprland) : ;;
 		kitty) command_exists "kitty" || die 3 "kitty is not installed\n" ;;
 		imv)
 			first_img="$(jq -r '.[0].ID|select(.!=null)' < "$ytfzf_video_json_file")"
@@ -1872,7 +1873,7 @@ preview_stop () {
 		kill "$mpv_pid"
 		rm "$MPV_SOCKET" > /dev/null 2>&1
 		;;
-	    swayimg) killall swayimg 2> /dev/null;;
+	    swayimg|swayimg-hyprland) killall swayimg 2> /dev/null;;
 	    imv) kill "$imv_pid" ;;
 	    *)
 		"$thumbnail_viewer" "stop" "$FZF_PREVIEW_COLUMNS" "$FZF_PREVIEW_LINES" 2>/dev/null ;;
@@ -1896,7 +1897,7 @@ preview_no_img (){
 		} > "$UEBERZUG_FIFO"
 			    ;;
 	    kitty) kitty +kitten icat --clear --transfer-mode file ;;
-	    swayimg) killall swayimg 2> /dev/null; true ;; # we want this to be true so that the && at the bottom happens
+	    swayimg|swayimg-hyprland) killall swayimg 2> /dev/null; true ;; # we want this to be true so that the && at the bottom happens
 	    *) "$thumbnail_viewer" "no-img" ;;
 	esac && do_an_event_function "on_no_thumbnail"
 
@@ -2020,6 +2021,40 @@ preview_display_image () {
 		    printf "}\n"
 		} > "$UEBERZUG_FIFO" 2> "$thumbnail_debug_log"
 		;;
+        swayimg-hyprland)
+            command_exists "hyprctl" || die 3 "hyprctl is required for this thumbnail viewer\n"
+            _swayimg_pid_file="${session_temp_dir}/_swayimg.pid"
+            [ -f "$_swayimg_pid_file" ] && kill "$(cat "$_swayimg_pid_file")" 2> /dev/null
+            command_exists "tput" || die 3 "tput is required for this viewer\n(you are probably missing ncurses)\n" 
+            window_data="$(hyprctl activewindow -j)"
+            read -r x y <<-EOF
+            $(printf "%s" "$window_data" |  jq -r '"\(.at[0]) \(.at[1])"')
+EOF
+            read -r w h <<-EOF
+            $(printf "%s" "$window_data" |  jq -r '"\(.size[0]) \(.size[1])"')
+EOF
+            read -r output_x output_y <<-EOF
+            $(hyprctl monitors -j |  jq -r '.[]|select(.focused==true) as $mon | "\($mon.x) \($mon.y)"')
+EOF
+            x=$((x-output_x))
+            y=$((y-output_y))
+            TTY_COLS=$(tput cols)
+            TTY_LINES=$(tput lines)
+            # shellcheck disable=SC2034
+            w_half=$((w/2)) h_half=$((h/2))
+            # how many pixels per col
+            col_px_width=$((w/TTY_COLS))
+            # how many pixels per line
+            line_px_height=$((h/TTY_LINES))
+            get_swayimg_positioning "$((w))" "$((h))" "$x" "$y" "$col_px_width" "$line_px_height"
+            hyprctl keyword windowrulev2 float,title:swayimg > /dev/null 2>&1
+            hyprctl keyword windowrulev2 nofocus,title:swayimg > /dev/null 2>&1
+            hyprctl keyword windowrulev2 "move $((x+10)) $y,title:swayimg" > /dev/null 2>&1
+            hyprctl keyword windowrulev2 "noborder,title:swayimg" > /dev/null 2>&1
+            swayimg -s fit -g $((x+10)),$y,$((img_w)),$((img_h)) "$thumb_path"  2> "$thumbnail_debug_log" >&2 &
+            printf "%s" "$!" > "$_swayimg_pid_file"
+            # without this there are weird flushing issues (maybe)
+            ;;
 	    swayimg)
             _swayimg_pid_file="${session_temp_dir}/_swayimg.pid"
             [ -f "$_swayimg_pid_file" ] && kill "$(cat "$_swayimg_pid_file")" 2> /dev/null
