excessive 0s when reseting colors

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -171,7 +171,7 @@ all_help_info () {
     printf "         Then taking the value of the &sp= part of the url\n";
     printf "         Filters may not work especially when the filter sorts for non-videos\n";
     printf "         In addition this overrides any filter provided through options\n";
-    printf "         Example: \033[1mytfzf --filter-id=EgJAAQ minecraft\033[000m\n";
+    printf "         Example: \033[1mytfzf --filter-id=EgJAAQ minecraft\033[0m\n";
     printf "         This will filter by livestream\n";
     printf "\n";
     printf "     --update                             clones the latest stable commit and installs it\n";
@@ -221,7 +221,7 @@ c_yellow="\033[1;33m"
 c_blue="\033[1;34m"
 c_magenta="\033[1;35m"
 c_cyan="\033[1;36m"
-c_reset="\033[000m"
+c_reset="\033[0m"
 
 
 #> To determine the length of each field (title, channel ... etc)
@@ -493,7 +493,7 @@ scrape_channel () {
 	yt_html="$(get_yt_html "$*")"
 
 	if [ -z "$yt_html" ]; then
-	        print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
+	        print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[0m\n"
 	        exit 1
 	fi
 
@@ -555,7 +555,7 @@ scrape_yt () {
 
 	yt_html="$(get_yt_html "https://www.youtube.com/results" "$*")"
 	if [ -z "$yt_html" ]; then
-		print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[000m\n"
+		print_error "\033[31mERROR[#01]: Couldn't curl website. Please check your network and try again.\033[0m\n"
 		exit 1
 	fi
 
@@ -563,7 +563,7 @@ scrape_yt () {
 
 	#if the data couldn't be found
 	if [ -z "$yt_json" ]; then
-		print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[000m\n"
+		print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[0m\n"
 		exit 1
 	fi
 
@@ -687,7 +687,7 @@ play_url () {
 		[ 4 -eq $? ] || eval "$YTFZF_PLAYER" "$player_urls"
                      # Ctr-C in MPV results in a return code of 4
 	} || {
-		print_error "\033[31mERROR[#03]: Couldn't play the video/audio using the current player: ${YTFZF_PLAYER}\n\t\033[000mTry updating youtube-dl\n"; save_before_exit ; exit 1;
+		print_error "\033[31mERROR[#03]: Couldn't play the video/audio using the current player: ${YTFZF_PLAYER}\n\t\033[0mTry updating youtube-dl\n"; save_before_exit ; exit 1;
 	}
 }
 #> Checks if other sessions are running, if not then deletes thumbnails
@@ -744,7 +744,7 @@ clear_history () {
 		echo "" > "$history_file"
 		printf "History has been cleared\n"
 	else
-		printf "\033[31mHistory file not found, history not cleared\033[000m\n"
+		printf "\033[31mHistory file not found, history not cleared\033[0m\n"
 		exit 1
 	fi
 }
@@ -889,9 +889,9 @@ parse_long_opt () {
 		fancy-subs=*) fancy_subscriptions_menu="${opt#*=}" ;;
 
 		version)
-		    printf "\033[1mytfzf:\033[000m %s\n" "$YTFZF_VERSION"
-		    printf "\033[1myoutube-dl:\033[00m %s\n" "$(youtube-dl --version)"
-		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[000m %s\n" "$(fzf --version)"
+		    printf "\033[1mytfzf:\033[0m %s\n" "$YTFZF_VERSION"
+		    printf "\033[1myoutube-dl:\033[0m %s\n" "$(youtube-dl --version)"
+		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[0m %s\n" "$(fzf --version)"
 		    exit ;;
 
 		*)
@@ -968,14 +968,14 @@ shift $((OPTIND-1))
 #if both are true, it defaults to using fzf, and if fzf isnt installed it will throw an error
 #so print this error instead and set $show_thumbnails to 0
 if [ $is_ext_menu -eq 1 -a $show_thumbnails -eq 1 ]; then
-	printf "\033[31mCurrently thumbnails do not work in external menus\033[000m\n"
+	printf "\033[31mCurrently thumbnails do not work in external menus\033[0m\n"
 	show_thumbnails=0
 fi
 
 #if stdin is given and no input (including -) is given, throw error
 #also make sure its not reading from ext_menu
 if [ ! -t 0 ] && [ -z "$*" ] && [ $is_ext_menu -eq 0 ]; then
-	printf "\033[31mERROR[#04]: Use - when reading from stdin\033[000m\n"
+	printf "\033[31mERROR[#04]: Use - when reading from stdin\033[0m\n"
 	exit 2
 #read stdin if given
 elif [ "$*" = "-" ]; then
