Style: shellcheck suggestions
- printf variables changed to printf "%s" variables
- read command with option -r
- removed -o and -a as they are not well defined, used && and || instead

diff --git a/ytfzf b/ytfzf
--- a/ytfzf
+++ b/ytfzf
@@ -105,7 +105,7 @@ fi
 #dependency check
 dep_ck () {
 	for dep in "$@"; do
-		command -v "$dep" 1>/dev/null || { printf "$dep not found. Please install it.\n" ; exit 2; }
+		command -v "$dep" 1>/dev/null || { printf "%s not found. Please install it.\n" "$dep" ; exit 2; }
 	done
 }
 dep_ck "jq" "youtube-dl";
@@ -317,7 +317,7 @@ preview_img () {
 	thumb_width=$WIDTH
 	thumb_height=$((HEIGHT - 2))
 	#most common x, y positions
-	thumb_x=$(($TTY_COLS / 2 + 3))
+	thumb_x=$((TTY_COLS / 2 + 3))
 	thumb_y=10
 	case "$PREVIEW_SIDE" in
 	    left)
@@ -329,7 +329,7 @@ preview_img () {
 		;;
 	    bottom)
 		thumb_height=$((HEIGHT - 5))
-		thumb_y=$(($TTY_LINES / 2 + 3))
+		thumb_y=$((TTY_LINES / 2 + 3))
 		;;
 	esac
 
@@ -356,7 +356,7 @@ download_thumbnails () {
 	[ "$show_link_only" -eq 0 ] && printf "Downloading Thumbnails"
     
 	i=0
-	while read line; do
+	while read -r line; do
 		if [ $((i % 2)) -eq 0 ]; then
 			url="$(echo "$line" | sed -E 's/^"//;s/\.png.*/\.png/')" 
 		else
@@ -495,8 +495,8 @@ get_search_query () {
 			search_query="$(printf "" | $YTFZF_EXTMENU)"
 		else
 			#otherwise use the search prompt
-			printf "$search_prompt"
-			read search_query
+			printf "%s" "$search_prompt"
+			read -r search_query
 		fi
 		[ -z "$search_query" ] && exit 0
 	fi
@@ -532,14 +532,14 @@ user_selection () {
 	fi
 	
 	#gets a list of video ids/urls from the selected data
-	shorturls="$(echo "$selected_data" | sed -E -e 's_.*\|([^|]+) *$_\1_')"
+	shorturls="$(echo "$selected_data" | sed -E -e "s_.*\|([^|]+) *\$_\1_")"
 	[ -z "$shorturls" ] && exit;
 
 	#for each url append the full url to the $urls string
 	#through this loop, the selected data which was truncated by formatting is retrived.
 	urls=""
 	selected_data=""
-	while read surl; do
+	while read -r surl; do
 		[ -z "$surl" ] && continue
 		urls="$(printf '%s\n%s' "${urls}" "https://www.youtube.com/watch?v=$surl")"
 		selected_data="$(printf '%s\n%s' "$selected_data" "$(echo "$videos_data" | grep -m1 -e "$surl" )")"
@@ -548,7 +548,7 @@ user_selection () {
 EOF
 	urls="$( printf "%s" "$urls" | sed 1d )"
 	#sometimes % shows up in selected data, could throw an error if it's an invalid directive
-	selected_data="$( printf "$selected_data" | sed 1d )"
+	selected_data="$( printf "%s" "$selected_data" | sed 1d )"
 
 	if [ "$show_link_only" -eq 1 ] ; then
 		echo "$urls"
@@ -557,17 +557,17 @@ EOF
 
 	# select format if flag given
 	if [ "$show_format" -eq 1 ]; then 
-		YTFZF_PREF="$(youtube-dl -F "$(printf "$urls" | sed 1q)" | sed '1,3d' | tac - |\
+		YTFZF_PREF="$(youtube-dl -F "$(printf "%s" "$urls" | sed 1q)" | sed '1,3d' | tac - |\
 		eval "$menu_command" | sed -E 's/^([^ ]*) .*/\1/')"
 		[ -z "$YTFZF_PREF"  ] && exit;
 	fi	
 }
 play_url () {
 	#> output the current track to current file before playing
-	[ "$YTFZF_CUR" -eq 1 ] && printf "$selected_data" > "$current_file" ;
+	[ "$YTFZF_CUR" -eq 1 ] && printf "%s" "$selected_data" > "$current_file" ;
 
 	#> The urls are quoted and placed one after the other for mpv to read
-	player_urls="\"$(printf "$urls" | awk  'ORS="\" \"" { print }' | sed 's/"$//' )"
+	player_urls="\"$(printf "%s" "$urls" | awk  'ORS="\" \"" { print }' | sed 's/"$//' )"
 	#> Play url with $player or $player_format based on options
 	#> if player format fails, then use normal player
 	[ -n "$YTFZF_PREF" ] && {
@@ -582,7 +582,7 @@ play_url () {
 #> Checks if other sessions are running, if not then deletes thumbnails
 delete_thumbnails () {
 	session_count=0
-	while read pid; do
+	while read -r pid; do
 		[ -d /proc/"$pid" ] && session_count=$(( session_count + 1 ))
 	done < "$pid_file"
 	if [ $session_count -eq 1 ] ; then
@@ -593,7 +593,7 @@ delete_thumbnails () {
 #> Save and clean up before script exits
 save_before_exit () {
 	[ "$is_url" -eq 1 ] && exit
-	[ "$YTFZF_HIST" -eq 1 ] && printf "$selected_data\n" >> "$history_file" ;
+	[ "$YTFZF_HIST" -eq 1 ] && printf "%s\n" "$selected_data" >> "$history_file" ;
 	[ "$YTFZF_CUR" -eq 1 ] && printf "" > "$current_file" ;
 }
 
@@ -605,8 +605,8 @@ save_before_exit () {
 check_if_url () {
 	# to check if given input is a url
 	url_regex='^https\?://.*'
-	echo "$1" | grep -q "$url_regex"
-	if [ $? -eq 0 ] ; then
+	
+	if { echo "$1" | grep -q "$url_regex"; } ; then
 		is_url=1
 		urls="$1"
 		scrape=0
@@ -711,13 +711,13 @@ parse_long_opt () {
 		update-unstable) update_ytfzf "development" ;;
 
 		version) 
-		    printf "\033[1mytfzf:\033[000m $YTFZF_VERSION\n"
-		    printf "\033[1myoutube-dl:\033[00m $(youtube-dl --version)\n"
-		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[000m $(fzf --version)\n"
+		    printf "\033[1mytfzf:\033[000m %s\n" "$YTFZF_VERSION"
+		    printf "\033[1myoutube-dl:\033[00m %s\n" "$(youtube-dl --version)"
+		    command -v "fzf" 1>/dev/null && printf "\033[1mfzf:\033[000m %s\n" "$(fzf --version)"
 		    exit ;;
 				
 		*)
-		    printf "Illegal option --$opt\n"
+		    printf "Illegal option --%s\n" "$opt"
 		    usageinfo
 		    exit 2 ;;
 	esac
@@ -758,7 +758,7 @@ parse_opt () {
 
 		t) 	show_thumbnails=1 ;;
 
-		v)	printf "ytfzf: $YTFZF_VERSION\n"
+		v)	printf "ytfzf: %s\n" "$YTFZF_VERSION"
 			exit ;;
 
 		L) 	show_link_only=1 ;;
@@ -782,21 +782,20 @@ done
 shift $((OPTIND-1))
 
 #if stdin is given and no input (including -) is given, throw error
-if [ ! -t 0 -a -z "$*" -a $is_ext_menu -eq 0 ]; then
+if [ ! -t 0 ] && [ -z "$*" ] && [ $is_ext_menu -eq 0 ]; then
 	printf "\033[31mERROR[#04]: Use - when reading from stdin\033[000m\n"
 	exit 1
 #read stdin if given
 elif [ "$*" = "-" ]; then
 	printf "Reading from stdin\n"
-	while read line
+	while read -r line
 	do
 	    search_query="$search_query $line"
 	done
 fi
-[ -n "$search_query" ] && is_stdin=1 || is_stdin=0
 check_if_url "${search_query:=$*}" 
 # If in auto select mode dont download thumbnails
-[ $auto_select -eq 1 -o $random_select -eq 1 ] && show_thumbnails=0; 
+[ $auto_select -eq 1 ] || [ $random_select -eq 1 ] && show_thumbnails=0; 
 
 #format the menu screen
 format_menu 
@@ -813,7 +812,7 @@ while true; do
 	save_before_exit
 	
 	#if looping and searching_again arent on then exit
-	if [ $YTFZF_LOOP -eq 0 -a $search_again -eq 0 ] ; then
+	if [ $YTFZF_LOOP -eq 0 ] && [ $search_again -eq 0 ] ; then
 		delete_thumbnails
 		exit
 	fi
